import {Injectable} from '@angular/core';
import {HttpEvent, HttpHandler, HttpHeaders, HttpInterceptor, HttpRequest} from '@angular/common/http';
import {Observable} from 'rxjs/Observable';
import {AuthService} from './auth.service';
import {Router} from '@angular/router';

@Injectable()
export class TokenInterceptor implements HttpInterceptor {

  constructor(public auth: AuthService, private router: Router) {
  }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    let newRequest;

    /** Authorization header is not allowed by '/login'
     * Token is generated by '/login' URL which should be sent in every other URL header **/
    if (request.url !== 'http://67.205.188.223:8000/login' && request.url !== 'https://fcm.googleapis.com/fcm/send'
      && !request.url.includes('http://talk.miraclesoft.com')) {
      if (this.auth.isAuthenticated()) {
        const headers = new HttpHeaders({
          'Authorization': `Bearer ${this.auth.getToken()}`,
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        });
        newRequest = request.clone({headers: headers});
        return next.handle(newRequest);
      } else {
        localStorage.removeItem('loggedIn');
        localStorage.removeItem('loggedInUser');
        this.router.navigate(['/home']);
      }
    }

    return next.handle(request);

  }
}
